#!/bin/bash

# Setup YAY
cd $HOME
sudo pacman -S --noconfirm git
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd $HOME

# Install esential packages
basePackages=(
  arandr
  bspwm
  chromium
  dmenu
  gvfs
  kitty
  lxappearance
  lxsession
  neovim
  nitrogen
  numlockx
  openssh
  pamixer
  pavucontrol
  picom
  playerctl
  pulseaudio
  pulseaudio-alsa
  rofi
  sxhkd
  ueberzug
  unrar
  vifm
  xf86-input-libinput
  xf86-video-nouveau
  xorg-server
  xorg-xinit
  xorg-xsetroot
  xsel
  zsh
)

addPackages=(
  adobe-source-sans-pro-fonts
  adobe-source-serif-pro-fonts
  github-cli
  libreoffice-fresh
  mplayer
  neofetch
  nodejs
  noto-fonts
  npm
  reflector
  ttf-caladea
  ttf-carlito
  ttf-dejavu
  ttf-linux-libertine-g
  ttf-roboto-mono
  ufw
  vlc
  yq
  zathura
  zathura-cb
  zathura-djvu
  zathura-pdf-mupdf
  zathura-ps
)

yay=(
  polybar
  consolas-font
  ttf-gentium-basic
)

sudo pacman -S --noconfirm ${basePackages[@]}
yay -S --noconfirm ${yay[@]}

# Oh-my-zsh
cd $HOME
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions

# Git config
git config --global user.name yesiddgarzon
git config --global user.email yesiddgarzon@gmail.com
git config --global color.ui true
git config --global core.editor nvim
ssh-keygen -t rsa -C yesiddgarzon@gmail.com
ssh -T git@github.com

# Clone dotfiles
cd $HOME
rm .zshrc
echo ".dotfiles" >> .gitignore
git clone --bare git@github.com:yesiddgarzon/.dotfiles.git $HOME/.dotfiles
alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
dotfiles checkout
dotfiles config --local status.showUntrackedFiles no
sudo cp ~/.config/zsh/gitstart /usr/local/bin

# Install more needed packages
sudo pacman -S --noconfirm ${addPackages[@]}

# Enable Firewall
sudo ufw enable
