#!/bin/bash

# Setup YAY
cd $HOME
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd $HOME

# Install esential packages
pacman=(
  arandr
  bspwm
  chromium
  dmenu
  gvfs
  kitty
  lxsession
  neovim
  nitrogen
  numlockx
  openssh
  pamixer
  pavucontrol
  picom
  playerctl
  pulseaudio
  pulseaudio-alsa
  rofi
  sxhkd
  ueberzug
  unrar
  vifm
  xf86-input-libinput
  xf86-video-nouveau
  xorg-server
  xorg-xinit
  xorg-xsetroot
  xsel
  zsh
)

yay=(
  polybar
)

sudo pacman -S --noconfirm ${pacman[@]}
yay -S --noconfirm ${yay[@]}

# Oh-my-zsh
cd $HOME
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions

# Git config
git config --global user.name yesiddgarzon
git config --global user.email yesiddgarzon@gmail.com
git config --global color.ui true
git config --global core.editor nvim
ssh-keygen -t rsa -C yesiddgarzon@gmail.com
ssh -T git@github.com

# Clone dotfiles
cd $HOME
rm .zshrc
git clone --bare https://github.com/yesiddgarzon/.dotfiles.git $HOME/.dotfiles
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
dotfiles checkout
dotfiles config --local status.showUntrackedFiles no
sudo cp ~/.config/zsh/gitstart /usr/local/bin
