#!/bin/bash

# System clock
timedatectl set-ntp true
timedatectl status

# Partitioning
cgdisk /dev/sda

# Format partitions
mkfs.vfat -F32 /dev/sda1
mkfs.ext4 /dev/sda2
mkfs.ext4 /dev/sda3
mkswap /dev/sda4

# Mount partitions
mount /dev/sda2 /mnt
mkdir -p /mnt/{home,boot/EFI}
mount /dev/sda1 /mnt/boot/EFI
mount /dev/sda3 /mnt/home
swapon /dev/sda4

# Base packages
pacstrap /mnt base base-devel linux linux-firmware nertworkmanager

# Fstab
genfstab -U /mnt >> /mnt/etc/fstab

# Copy install scripts
cp -rfv archInstall /mnt/root
cp -rfv archPostInstall /mnt/root
cp -rfv sudoers /mnt/root
chmod +x /mnt/root/archInstall
chmod +x /mnt/root/archPostInstall

# Chroot
arch-chroot /mnt /root/archInstall

# Exit after run archInstall script
umount -R /mnt
reboot
