#!/bin/bash

# Add important packages
clear
echo ">>> Inserting info needed to configure the system"
read -p "Enter hostname: " hostname
read -p "Enter username: " user
clear
echo "==> Installing required packages"
{
  pacman -S --noconfirm sudo nano git curl linux-headers 
} &> /dev/null
echo "$(tput setaf 2) -> $(tput sgr0)Packages Installed"

echo "==> Arch linux system configuration"

# Time zone
{
ln -sf /usr/share/zoneinfo/America/Bogota /etc/localtime
hwclock --systohc
} &> /dev/null
echo "$(tput setaf 2) -> $(tput sgr0)Time zone configured"

# Localization
{
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
echo KEYMAP=es > /etc/vconsole.conf
} &> /dev/null
echo "$(tput setaf 2) -> $(tput sgr0)Language settle"

# Networking
echo "==> Adding hostname and edit hosts"
{
echo $hostname > /etc/hostname
echo "127.0.0.1   localhost" >> /etc/hosts
echo "::1   localhost" >> /etc/hosts
echo "127.0.1.1   $hostname.localdomain   $hostname" >> /etc/hosts
} &> /dev/null
echo "$(tput setaf 2) -> $(tput sgr0)Hostname and hosts configured"

# Root pass
echo "==> Changing root password"
passwd

# Bootloader
echo "==> Installing bootloader (Grub)"
{
pacman -S --noconfirm grub efibootmgr os-prober dosfstools mtools ntfs-3g
grub-install --target=x86_64-efi --efi-directory=/boot/EFI --bootloader-id=Grub --recheck
grub-mkconfig -o /boot/grub/grub.cfg
} &> /dev/null
echo "$(tput setaf 2) -> $(tput sgr0)Bootloader Installed succesfully"

# Create user and permissions
echo "==> Adding user"
useradd -m -G wheel,video,audio,input,power,storage,optical $user
echo "==> Setting user password"
passwd $user
echo "$(tput setaf 2) -> $(tput sgr0)User $user created successfully, press any key to edit permissions"
mv /root/sudoers /etc/sudoers
read tmpvar

# Internet
echo "==> Installing internet manager"
{
systemctl enable NetworkManager
} &> /dev/null
echo "$(tput setaf 2) -> $(tput sgr0)Network Manager configured successfully"

# User directories
echo "==> Creating user directories"
{
pacman -S --noconfirm xdg-user-dirs
xdg-user-dirs-update
} &> /dev/null
echo "$(tput setaf 2) -> $(tput sgr0)User directories created"

# Scripts 
mv /root/archPostInstall /home/$user/
echo "alias dotfiles='/usr/bin/git --git-dir=/home/$user/.dotfiles/ --work-tree=/home/$user'" >> /home/$user/.bashrc

echo "$(tput setaf 2)==> System configuration done successfully"
echo "$(tput setaf 2)==> Time to exit... press any key to do it"
read tmpvar
exit
