#!/bin/bash

# Setting up requirements
echo "alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'" >> $HOME/.bashrc
reset
{
sudo pacman -S --noconfirm git curl wget base-devel
} &> /dev/null
echo "$(tput setaf 2)✓ $(tput sgr0)Requirements settle, press any key to continue..."
read tmpvar

# Setup YAY
cd $HOME
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd $HOME

# Install esential packages
pacman=(
  gvfs
  lxappearance
  lxsession
  neovim
  nitrogen
  numlockx
  pamixer
  pavucontrol
  playerctl
  pulseaudio
  pulseaudio-alsa
  ueberzug
  unrar
  vifm
  xsel
  zsh
  adobe-source-sans-pro-fonts
  adobe-source-serif-pro-fonts
  github-cli
  libreoffice-fresh
  mplayer
  neofetch
  nodejs
  noto-fonts
  npm
  reflector
  ttf-caladea
  ttf-carlito
  ttf-dejavu
  ttf-linux-libertine-g
  ttf-roboto-mono
  ufw
  vlc
  yq
  zathura
  zathura-cb
  zathura-djvu
  zathura-pdf-mupdf
  zathura-ps
)

yay=(
  polybar
  consolas-font
  ttf-gentium-basic
)

{
sudo pacman -S --noconfirm ${pacman[@]}
yay -S --noconfirm ${yay[@]}
} &> /dev/null
echo "$(tput setaf 2)✓ $(tput sgr0)Basic Packages Installed"

# Oh-my-zsh
cd $HOME
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
{
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
} &> /dev/null
echo "$(tput setaf 2)✓ $(tput sgr0)Zsh installed and configured succesfully"

# Git config
git config --global user.name yesiddgarzon
git config --global user.email yesiddgarzon@gmail.com
git config --global color.ui true
git config --global core.editor nvim
ssh-keygen -t rsa -C yesiddgarzon@gmail.com
echo ">>> Time to go to github and add SSH key"
echo ">>> Press any key when ready..."
read tmpvar
ssh -T git@github.com

# Clone dotfiles
cd $HOME
rm .zshrc
{
git clone --bare git@github.com:yesiddgarzon/.dotfiles.git $HOME/.dotfiles
alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
} &> /dev/null
echo "$(tput setaf 2)✓ $(tput sgr0)Dotfiles cloned succesfully, press any key to continue"
read tmpvar
dotfiles checkout
dotfiles config --local status.showUntrackedFiles no
sudo cp ~/.config/zsh/gitstart /usr/local/bin

# Enable Firewall
sudo ufw enable

echo "$(tput setaf 2)✓✓✓ $(tput sgr0)Configuration done. You can now exit."
