#!/bin/bash

# Clone dotfiles
clear
echo "==> Cloning dotfiles repository"
cd $HOME
rm .zshrc
git clone --bare https://github.com/yesiddgarzon/.dotfiles.git $HOME/.dotfiles &> /dev/null
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
dotfiles checkout

read tmpvar


echo "$(tput setaf 2) -> $(tput sgr0)Dotfiles cloned succesfully"
dotfiles checkout
dotfiles config --local status.showUntrackedFiles no

# Git Configuration
echo "==> Making global git configurations"
git config --global user.name yesiddgarzon
git config --global user.email yesiddgarzon@gmail.com
git config --global color.ui true
git config --global core.editor nvim

# Copy scripts to PATH
echo "==> Copying zsh and vifm scripts to path"
sudo cp ~/.config/zsh/gitstart /usr/local/bin
sudo cp ~/.config/vifm/scripts/vifmimg /usr/local/bin
sudo cp ~/.config/vifm/scripts/vifmrun /usr/local/bin
